- .gitignore
- README.md
- index.js
- lib/wasmboy.js
- lib/wasmboyControllerState.js
- package-lock.json
- package.json
- wasm/cpu/index.ts
- wasm/cpu/opcodes.ts
- wasm/graphics/background.ts
- wasm/graphics/graphics.ts
- wasm/graphics/lcd.ts
- wasm/graphics/renderUtils.ts
- wasm/graphics/sprites.ts
- wasm/graphics/window.ts
- wasm/interrupts/index.ts
- wasm/memory/index.ts
- wasm/memory/memory.ts
- wasm/memory/readTraps.ts
- wasm/memory/store.ts
- wasm/memory/writeTraps.ts
- wasm/timers/index.ts
Oh and I also swapped "z" and "x"
Good Reference material for a post mortem:
https://www.reddit.com/r/EmuDev/comments/6fmjch/gb_glitches_in_links_awakening_and_pok%C3%A9mon_gold/
http://gbdev.gg8.se/wiki/articles/Video_Display#Accessing_VRAM_and_OAM
https://www.reddit.com/r/EmuDev/comments/6fmjch/gb_glitches_in_links_awakening_and_pok%C3%A9mon_gold/
https://www.reddit.com/r/EmuDev/comments/5kb3l6/how_would_i_debug_these_visual_glitches_in_my_gb/
https://www.reddit.com/r/EmuDev/comments/6r6gf3/gb_pokemon_gold_spews_unexpected_values_at_mbc/
> Fixed a handful of graphical and timing bugs

- .gitignore
- README.md
- wasm/cpu/opcodes.ts
- wasm/memory/load.ts
- wasm/memory/memory.ts
- wasm/memory/store.ts
Like almost all the games work now :')
Huge thanks to https://www.reddit.com/r/EmuDev/comments/7y2bux/gameboy_gb_graphical_bugs_game_writes_zeroes_into/dudlj3w/
See the issue outlined at: https://www.reddit.com/r/EmuDev/comments/7y2bux/gameboy_gb_graphical_bugs_game_writes_zeroes_into/
> FIXED THE TILE MAP BUG!!!

- .gitignore
- README.md
- index.js
- lib/memory/memory.js
- lib/wasmboy.js
- package-lock.json
- package.json
- preact.config.js
Using the node module [gh-pages](https://www.npmjs.com/package/gh-pages), we now have a live [Debugger / demo](https://torch2424.github.io/wasmBoy/). Hooray!
Did this so early on, to get some tester feedback on things like saving, and any other bugs my buddies might find :)
> Github Pages Setup

- .gitattributes
Just in case assemblyscript ever gets on linguist :)
> Added AsseblyScript gitattributes

- lib/audio/audio.js
- lib/graphics/graphics.js
- lib/memory/memory.js
- lib/wasmboy.js
- wasm/constants/constants.ts
- wasm/cpu/cpu.ts
- wasm/index.ts
- wasm/memory/memory.ts
closes #37 
Removed the function calls for the constants file, and made them simple properties
> [WIP] Shared Constants

- index.js
- manifest.json
As the title states! Now the add to homescreen doesn't just drop you off on my old blog, and it will open in landscape mode on phones!
#Example Screenshot
> Updated Manifest to be a usable PWA

- .gitignore
- index.js
- wasm/graphics/backgroundWindow.ts
- wasm/graphics/tiles.ts
- wasm/memory/dma.ts
> Tile Rendering And Caching Horizontal Mirroring

- debugger/index.js
- debugger/wasmboyFilePicker/googlePicker/googlePicker.js
- debugger/wasmboyFilePicker/wasmboyFilePicker.css
- debugger/wasmboyFilePicker/wasmboyFilePicker.js
- debugger/wasmboyOptions/wasmboyOptions.js
- debugger/wasmboySystemControls/wasmboySystemControls.css
- debugger/wasmboySystemControls/wasmboySystemControls.js
- index.js
- lib/wasmboy.js
- package-lock.json
- package.json
> Added a Google Drive File Selector to the Debugger

- debugger/wasmboyFilePicker/googlePicker/googlePicker.js
- debugger/wasmboyFilePicker/wasmboyFilePicker.js
- index.js
- lib/wasmboy.js
> Removed some Debugging Logs

- lib/audio/audio.js
- lib/memory/memory.js
- lib/wasmboy.js
Safari has some weird audio going on. And unfortunately, does not seem like mobile iOS [has any if at all decent support for wasm](https://bugs.webkit.org/show_bug.cgi?id=181781#c4).
> Some Safari Fixes

- README.md
- package.json
Starting work on Vaporboy, and need to soft launch for `npm install` :)
> Soft Launch on NPM For vaporboy

- index.js
- lib/index.js
- lib/wasmboy/update.js
- lib/wasmboy/wasmboy.js
- package.json
We can now set the canvas Element at anytime. This will be needed by VaporBoy for dynamic layout rendering 😄
> setCanvas() - Can now set canvas element at anytime

- core/graphics/backgroundWindow.ts
- core/sound/sound.ts
- package-lock.json
- package.json
This is to get the np lib:deploy working 😄
> Fixed some linting errors

- manifest.json
- preact.config.js
Now the debugger is at https://wasmboy.app ! 😄 🚢
> Fixed public path and things for custom domains

- package.json
See: https://github.com/tschaub/gh-pages/issues/127
> Added our cutom domain to our deploy process

- debugger/wasmboyFilePicker/wasmboyFilePicker.js
- lib/memory/memory.js
- lib/wasmboy/rom.js
- lib/wasmboy/wasmboy.js
As the title states. I think google drive changed their download URL implementation and it screwed it all up 😢 
Will require both a lib and a debugger deploy
> Fixed Google Drive and ROM Loading for Debugger

- index.js
- lib/audio/audio.js
- lib/graphics/graphics.js
- lib/memory/state.js
- lib/wasmboy/wasmboy.js
- package-lock.json
- package.json
The option callbacks allow for things like lowpass filters, and grayscaled images on audio and graphics. Similar to the save state callbacks, will allow for applications using the lib to build on top of wasmboy for fun/new gameplay :)
> Added the Callbacks that were mentioned in the Lib API

- lib/controller/controller.js
As the title States. This should fix things for vaporBoy. 😄 
Also, Made the controller less promise based to match responsive-gamepad
> Fixed the gamepad re-initializing on ROM load

- README.md
- core/core.ts
- core/cpu/cpu.ts
- core/graphics/graphics.ts
- core/memory/memory.ts
- core/sound/accumulator.ts
- core/sound/sound.ts
- core/timers/timers.ts
- index.js
- lib/index.js
- lib/wasm/instantiate.js
- lib/wasmboy/wasmboy.js
closes #123 
closes #126 
closes #119 
closes #120 
closes #121 
closes #125 
closes #128 
This fixes a lot of bugs I had made while making [VaporBoy](https://github.com/torch2424/vaporBoy). This fixes some major bugs, and adds some nice helper functions for implementing an application on top of wasmboy.
> Various Bug Fixes - Implemented or VaporBoy

- debugger/wasmboyDebugger/wasmboyDebugger.js
- package-lock.json
To get some new Assemblyscript awesomeness
> Updated the package-lock

- index.js
This is a fix so we can deploy the debugger 😄
> Wrapped load-script in window check for preact cli

- core/core.ts
- core/cpu/flags.ts
- core/index.ts
- core/legacy.ts
- debugger/wasmboySystemControls/wasmboySystemControls.js
- lib/memory/memory.js
- lib/wasmboy/wasmboy.js
- package-lock.json
- package.json
closes #135 
closes #134 
closes #133 
As the title states! Super awesome to be on the latest AssemblyScript, and should be helpful for Vaporboy!
> Finished updating core for new version of AS & Other small fixes

- lib/wasmboy/wasmboy.js
> Removed bad log

- core/core.ts
closes #144 
This is from a bug that I found on Assemblyscript: https://github.com/AssemblyScript/assemblyscript/issues/266
Now we can get VaporBoy into Public beta! 😄
> Removed defaults from core config() for Assemblyscript Bug

- README.md
- package-lock.json
- package.json
- rollup.config.js
Just some small housekeeping changes. Now we have lib build sizes in the actual build output logs
> Wiki and build updates

- debugger/wasmboyFilePicker/wasmboyFilePicker.js
- debugger/wasmboyOptions/wasmboyOptions.js
- debugger/wasmboySystemControls/wasmboySystemControls.js
- index.js
- lib/3p/UZIP.js
- lib/wasmboy/rom.js
- lib/wasmboy/wasmboy.js
- package-lock.json
- package.json
- rollup.config.js
closes #148 
closes #138 
closes #127 
Should have shrunk the build size in nearly half, and cleaned up some of my personal pet peeves with the API. Also, added some more analytics stuff on the debugger so we can understand how often games are breaking.
Also integrated https://github.com/photopea/UZIP.js for a much smaller ZIP file processing solution
> Lib/Debugger Improvements

- index.js
- package-lock.json
- package.json
- rollup.config.js
> Made some changes to build system to get things building correctly again

- lib/index.js
- test/accuracy/accuracy-test.js
Not sure how to test this enhancement, but decided to use a lambda expression to return constant from package.json like how the version is extracted in debugger.
> Issue #171: Adding getVersion function in lib.

- core/timers/timers.ts
This PR might get an award for the tinyest PR ever submitted. But little by little, the bird builds its nest, right? ;-)
> Fix minor typo

- lib/wasmboy/worker/memory/header.js
- lib/wasmboy/worker/memory/ram.js
- lib/wasmboy/worker/memory/rom.js
- lib/wasmboy/worker/update.js
Bug that slipped through not having enough test roms 😢
> Fixed ROMs with no RAM

- core/sound/sound.ts
Nothing to say really, I've just found a comment typo while reading the source. :)
> Fix minor comment typo

- demo/debugger/commands/widgets/audio.js
- demo/debugger/components/audio/frequency/frequency.js
- demo/debugger/components/audio/visualizer.css
- demo/debugger/components/audio/visualizer.js
- demo/debugger/components/audio/waveform/waveform.css
- demo/debugger/components/audio/waveform/waveform.js
- demo/debugger/widgetManager.js
relates to #244 
relates to #217 
This also moves around some code, to move the wave form visualizer code, into its own base class, that these two components can now share 😄
> Created an Audio Frequency Visualizer

- demo/debugger/commands/widgets/audio.js
- demo/debugger/components/audio/visualizer.js
- demo/debugger/components/audio/wavetable/wavetable.css
- demo/debugger/components/audio/wavetable/wavetable.js
- demo/debugger/widgetManager.js
closes #217 
Confirmed the wavetable with: http://gbdev.gg8.se/wiki/articles/Wavetable_Archive
> Added a wave table visualizer

- core/portable/wasmMock.js
- demo/amp/index.js
- demo/benchmark/loadrom.js
- package.json
As the title states. Should fix anything depending on the closure TS core. 😄 
Confirmed as well, that the benchmark was the only thing that was broken.
> Fixed the benchmark because of the fetch object change

- demo/debugger/commands/open.js
- demo/debugger/components/playback/wasmboyControls/wasmboyControls.css
- demo/debugger/components/playback/wasmboyControls/wasmboyControls.js
- demo/debugger/styles/commands.css
- demo/debugger/wasmboy.js
- lib/index.js
- lib/memory/memory.js
- lib/wasmboy/loadrom.js
- lib/wasmboy/wasmboy.js
closes #238
* Allowed Deleting Save States
* Limiting Auto Save States through config
* Deleting Saved Cartridge ROM
> Finished CRUD operations for save states and saved cartridge roms

- demo/debugger/components/audio/visualizer.js
- demo/debugger/wasmboy.js
- lib/audio/gbchannel.js
- lib/graphics/graphics.js
- lib/index.js
- lib/memory/state.js
- lib/plugins/plugins.js
- lib/wasmboy/load.js
- lib/wasmboy/onmessage.js
- lib/wasmboy/wasmboy.js
closes #223 
This is a much cleaner / easier API to use compared to the "Callback" system in config. May want to move everything that doesn't require a restart to a setting in the plugin if possible.
> Created a plugin API 🔌

- lib/audio/gbchannel.js
Fixed the Safari Issue being logged to the console in the wasmboy demo.
> Fixed closure compiled output for safari

- demo/amp/index.html
- demo/amp/index.js
As the title states!
View is broken, but can be fixed later 🤷‍♂
> Some AMP Script height fixes, and Implemented origin trial

- demo/amp/index.html
> Put the right amp-script token

- core/portable/importObject.js
- package-lock.json
> Updated deps, and confirmed working with new AssemblyScript runtime

- .travis.yml
- lib/memory/idb.js
- package.json
- test/integration/integration-test.js
> Fixed Node Save States, and added a test

- demo/wasmerboy/wapm.toml
As the title states 😄 
relates to #316
> Published wasmerboy 0.1.1

- README.md
Added `torch2424/wasmerboy` wapm package badge to the README :)
It will show like:
[![wapm version](https://wapm.io/package/torch2424/wasmerboy/badge.svg?style=flat)](https://wapm.io/package/torch2424/wasmerboy)
> Added wapm badge

- demo/iframe/components/About.svelte
> Added a shoutout for the iframe

- README.md
> Updated Iframe Embed README Docs for FullScreen

- package-lock.json
- package.json
Just runs `npm audit fix` to update all the appropriate dependencies :smile: :+1:
> Updated dependcies with npm audit fix

- core/graphics/graphics.ts
> Updated LCDC initial value to 0x91
